cp src/include/page/b_plus_tree_page.h ~/cmuDB/src/include/page/b_plus_tree_page.h
cp src/page/b_plus_tree_page.cpp ~/cmuDB/src/page/b_plus_tree_page.cpp
cp src/include/page/b_plus_tree_internal_page.h ~/cmuDB/src/include/page/b_plus_tree_internal_page.h
cp src/page/b_plus_tree_internal_page.cpp ~/cmuDB/src/page/b_plus_tree_internal_page.cpp
cp src/include/page/b_plus_tree_leaf_page.h ~/cmuDB/src/include/page/b_plus_tree_leaf_page.h
cp src/page/b_plus_tree_leaf_page.cpp ~/cmuDB/src/page/b_plus_tree_leaf_page.cpp
cp src/include/index/b_plus_tree.h ~/cmuDB/src/include/index/b_plus_tree.h
cp src/index/b_plus_tree.cpp ~/cmuDB/src/index/b_plus_tree.cpp
cp src/include/index/index_iterator.h ~/cmuDB/src/include/index/index_iterator.h
cp src/index/index_iterator.cpp ~/cmuDB/src/index/index_iterator.cpp